In [47]:
#1. Import the NUMPY package under the name np.
import numpy as np


In [48]:
#2. Print the NUMPY version and the configuration.
!pip freeze | grep numpy

numpy==1.17.2


In [49]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random ((2,3,5))

In [50]:
#4. Print a.
print (a)

[[[0.89412651 0.85172407 0.13992933 0.64932018 0.30899008]
  [0.75301444 0.16791655 0.03229269 0.89133506 0.55108289]
  [0.89718996 0.26719242 0.6701981  0.23944879 0.74756902]]

 [[0.08520831 0.92669143 0.19172307 0.69269094 0.08619434]
  [0.59911762 0.10771134 0.23874171 0.77384604 0.20604063]
  [0.13159424 0.489388   0.29999865 0.10705094 0.99564617]]]


In [51]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.zeros ((5,2,3))

In [52]:
#6. Print b.
print (b)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [53]:
#7. Do a and b have the same size? How do you prove that in Python code?
np.shape (a) == np.shape (b)

False

In [54]:
#8. Are you able to add a and b? Why or why not?

#No, cos they don't have the same size.

In [55]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). 
#Assign the transposed array to varialbe "c".
c = b.reshape (2,3,5)
print(c)
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[[[0.89412651 0.85172407 0.13992933 0.64932018 0.30899008]
  [0.75301444 0.16791655 0.03229269 0.89133506 0.55108289]
  [0.89718996 0.26719242 0.6701981  0.23944879 0.74756902]]

 [[0.08520831 0.92669143 0.19172307 0.69269094 0.08619434]
  [0.59911762 0.10771134 0.23874171 0.77384604 0.20604063]
  [0.13159424 0.489388   0.29999865 0.10705094 0.99564617]]]


In [56]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c

In [57]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print (a)
print (d)

[[[0.89412651 0.85172407 0.13992933 0.64932018 0.30899008]
  [0.75301444 0.16791655 0.03229269 0.89133506 0.55108289]
  [0.89718996 0.26719242 0.6701981  0.23944879 0.74756902]]

 [[0.08520831 0.92669143 0.19172307 0.69269094 0.08619434]
  [0.59911762 0.10771134 0.23874171 0.77384604 0.20604063]
  [0.13159424 0.489388   0.29999865 0.10705094 0.99564617]]]
[[[0.89412651 0.85172407 0.13992933 0.64932018 0.30899008]
  [0.75301444 0.16791655 0.03229269 0.89133506 0.55108289]
  [0.89718996 0.26719242 0.6701981  0.23944879 0.74756902]]

 [[0.08520831 0.92669143 0.19172307 0.69269094 0.08619434]
  [0.59911762 0.10771134 0.23874171 0.77384604 0.20604063]
  [0.13159424 0.489388   0.29999865 0.10705094 0.99564617]]]


In [58]:
#12. Multiply a and c. Assign the result to e.
e = a * c

In [59]:
#13. Does e equal to a? Why or why not?
np.shape (e) == np.shape (a)

True

In [60]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.amax(d)
print(d_max)
d_min = np.amin(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

0.9956461669232283
0.03229268540400432
0.4664324500569811


In [61]:
#15. Now we want to label the values in d. 
#First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty ([2,3,5])
print(f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [88]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.

for x,y in d,f:
    for k,v,j in x,y,z:
        for i,z in k,v:
                     np.where(d == d_mean, 50, f) 
                #elif i == d_min:
                 #    z = 0
                #elif i == d_max:
                 #    z = 100
                #elif d_min < i < d_mean:
                 #    z = 25
                #elif d_mean < i < d_max:
                #     z = 75            
print(f)               



ValueError: too many values to unpack (expected 2)

In [37]:
#17. Print d and f. Do you have your expected f?
#For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

#Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

NameError: name 'array' is not defined

In [ ]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.