In [27]:
#1. Import the NUMPY package under the name np.
import numpy as np


In [28]:
#2. Print the NUMPY version and the configuration.
!pip freeze | grep numpy

numpy==1.17.2


In [29]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random ((2,3,5))

In [30]:
#4. Print a.
print (a)

[[[0.0042205  0.20827069 0.54977793 0.2570855  0.88169368]
  [0.69334548 0.38962707 0.58634714 0.18408287 0.00198113]
  [0.99614523 0.63432761 0.10084039 0.87888807 0.29773102]]

 [[0.77015482 0.9387764  0.23934335 0.34730139 0.49943491]
  [0.01090752 0.92061482 0.17727348 0.0588388  0.25811895]
  [0.82281798 0.02463461 0.87282068 0.99115233 0.71260933]]]


In [31]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.zeros ((5,2,3))

In [32]:
#6. Print b.
print (b)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [33]:
#7. Do a and b have the same size? How do you prove that in Python code?
np.shape (a) == np.shape (b)

False

In [34]:
#8. Are you able to add a and b? Why or why not?

#No, cos they don't have the same size.

In [35]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). 
#Assign the transposed array to varialbe "c".
c = b.reshape (2,3,5)
print(c)
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[[[0.0042205  0.20827069 0.54977793 0.2570855  0.88169368]
  [0.69334548 0.38962707 0.58634714 0.18408287 0.00198113]
  [0.99614523 0.63432761 0.10084039 0.87888807 0.29773102]]

 [[0.77015482 0.9387764  0.23934335 0.34730139 0.49943491]
  [0.01090752 0.92061482 0.17727348 0.0588388  0.25811895]
  [0.82281798 0.02463461 0.87282068 0.99115233 0.71260933]]]


In [36]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c

In [37]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print (a)
print (d)

[[[0.0042205  0.20827069 0.54977793 0.2570855  0.88169368]
  [0.69334548 0.38962707 0.58634714 0.18408287 0.00198113]
  [0.99614523 0.63432761 0.10084039 0.87888807 0.29773102]]

 [[0.77015482 0.9387764  0.23934335 0.34730139 0.49943491]
  [0.01090752 0.92061482 0.17727348 0.0588388  0.25811895]
  [0.82281798 0.02463461 0.87282068 0.99115233 0.71260933]]]
[[[0.0042205  0.20827069 0.54977793 0.2570855  0.88169368]
  [0.69334548 0.38962707 0.58634714 0.18408287 0.00198113]
  [0.99614523 0.63432761 0.10084039 0.87888807 0.29773102]]

 [[0.77015482 0.9387764  0.23934335 0.34730139 0.49943491]
  [0.01090752 0.92061482 0.17727348 0.0588388  0.25811895]
  [0.82281798 0.02463461 0.87282068 0.99115233 0.71260933]]]


In [38]:
#12. Multiply a and c. Assign the result to e.
e = a * c

In [39]:
#13. Does e equal to a? Why or why not?
np.shape (e) == np.shape (a)

True

In [40]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.amax(d)
print(d_max)
d_min = np.amin(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

0.9961452312936099
0.0019811280149993893
0.4769721220027902


In [41]:
#15. Now we want to label the values in d. 
#First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty ([2,3,5])
print(f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [42]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.
d_list = list(d)
f_list = [[[0 if i == d_min else 50 if i == d_mean else 100 if i == d_max else 25 if i < d_mean and i > d_min else 75 for i in y] for y in x] for x in d_list]
f = np.array (f_list)
print (f)

[[[ 25  25  75  25  75]
  [ 75  25  75  25   0]
  [100  75  25  75  25]]

 [[ 75  75  25  25  75]
  [ 25  75  25  25  25]
  [ 75  25  75  75  75]]]


In [49]:
# #17. Print d and f. Do you have your expected f?
# #For instance, if your d is:
# # array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
#         [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
#         [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

#        [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
#         [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
#         [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

# #Your f should be:
# # array([[[ 75.,  75.,  75.,  25.,  75.],
#         [ 75.,  75.,  25.,  25.,  25.],
#         [ 75.,  25.,  75.,  75.,  75.]],

#        [[ 25.,  25.,  25.,  25., 100.],
#         [ 75.,  75.,  75.,  75.,  75.],
#         [ 25.,  75.,   0.,  75.,  75.]]])

In [47]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
# ("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
# array([[[ 'D',  'D',  'D',  'B',  'D'],
#         [ 'D',  'D',  'B',  'B',  'B'],
#         [ 'D',  'B',  'D',  'D',  'D']],

#        [[ 'B',  'B',  'B',  'B',  'E'],
#         [ 'D',  'D',  'D',  'D',  'D'],
#         [ 'B',  'D',   'A',  'D', 'D']]])
# Again, you don't need Numpy in this question.
f_list = list(f)
g_list = [[['A' if i == 0 else 'C' if i == 50 
            else 'E' if i == 100 else 'B' if i == 25 
            else 'D' for i in y] for y in x] for x in f_list]
g = np.reshape (g_list, (2, 3, 5))
print (g)

[[['B' 'B' 'D' 'B' 'D']
  ['D' 'B' 'D' 'B' 'A']
  ['E' 'D' 'B' 'D' 'B']]

 [['D' 'D' 'B' 'B' 'D']
  ['B' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]]
